web:
  build: .
  environment:
    MYENV: EXAMPLE
  volumes:
    - .:/wistlerator
web_migrate:
  extends:
    service: web
  command: python wistlerator/manage.py migrate
web_run:
  extends:
    service: web
  command: python wistlerator/manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"