# Generated by Django 3.1.4 on 2020-12-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MediaCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=25)),
                ('postal_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'MediaCompanies',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('arrival_date', models.DateField(verbose_name='arrival date')),
                ('content', models.CharField(max_length=1000)),
                ('comments', models.CharField(blank=True, max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='samples.category')),
            ],
        ),
    ]
